# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meet Lolla
email: tatimblin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lollapalooza is an annual three day music festival in Chicago, IL 
  featuring over 100 different artists. meetlolla.com's goal is to
  give you a preview of some of these artists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meetlolla.com" # the base hostname & protocol for your site
permalink: /artist/:title
twitter_username: TristanTimblin
github_username:  tatimblin

# Build settings
markdown: kramdown